config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # root "groups#new"
  root "groups#index"
  # resources :users, only: [:show, :edit, :update]
  resources :users, only: [:index, :edit, :update]
  resources :groups, except: [:show, :destroy] do
    resources :messages, only: [:index, :create]
  end
  resources :members


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  # has_many :users, through: :members
  has_many :users, through: :members
  has_many :members, dependent: :destroy
  has_many :messages


  # name属性に値がない場合にエラー
  validates :name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :body_or_image, presence: true

  private
  def body_or_image
    body.presence or image.presence
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :members
  has_many :members, dependent: :destroy
  has_many :messages

  scope :search_name, -> (keyword) { where('name LIKE(?)', "%#{keyword}%").limit(20) }
  scope :exclude_currentUser, -> (current_user) { where.not(id: current_user.id) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def configure_permitted_parameters
      # added_attrs = [ :name, :email, :password, :password_confirmation ]
      # devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      # devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
      # sign_inのときに、nameも許可する
      devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
    # sign_upのときに、nameも許可する
      devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
    #account_updateのときに、nameも許可する
      devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :find_group, only: [:edit, :update]
  before_action :find_members, only: [:new, :edit, :update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group)
    else
      flash.now[:alert] = "グループ作成失敗"
      render action: :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "グループを更新しました。"
    else
      flash.now[:alert] = "グループ更新失敗"
      render action: :edit
    end
  end

  def find_group
    @group = Group.find(params[:id])
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def find_members
    @members = @group.users
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :member_new, only: [:index,:new]

  def index

  end

  def new

  end

  def create

  end

  def member_new
    @member = Member.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_message, only: [:index,:new]
    before_action :group_id_find, only: :create

  def index
    @groups = current_user.groups
    begin
      @group = Group.find(params[:group_id])
    rescue
      redirect_to root_path
    else
      @messages = @group.messages.includes(:user)
      @member = @group.users
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) , notice: "メッセージを送信しました。" }
        format.json
      end
    else
      redirect_to group_messages_path(@group), alert: "メッセージを入力してください。"
    end
  end

  private
  def set_message
    @message = Message.new
  end

  def group_id_find
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:body, :image, :image_cache).merge(user_id: current_user.id, group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search_name(params[:keyword]).exclude_currentUser(current_user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit

  end

  def update
    if current_user.update(update_params)
      redirect_to :root, notice: "編集完了しました。"
    else
      flash.now[:alert] = "編集に失敗しました。"
      render action: :edit
    end
  end

  def update_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
  def time_format(post_time)
    post_time.strftime('%Y/%m/%d %H:%M')
  end
end

app/views/groups/_form.html.haml
= form_for @group do |f|

  -if @group.errors.any?
    .chat-group-form__errors
      #error_explanation
        %h2= "#{ (@group.errors.count) } 件のエラーがあります。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg


  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名",:name , class: "chat-group-form__label",for: "chat_group_name"
    .chat-group-form__field--right
      = f.text_field :name ,placeholder: "グループ名を入力してください" ,class: "chat-group-form__input", id: "chat_group_name"

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"}チャットメンバーを追加
    .chat-group-form__field--right
      %input{type: "text", placeholder: "追加したいユーザー名を入力してください", class: "chat-group-form__input", id: "user-search-field"}
      .chat-group-form__search.clearfix
        .chat-group-user.clearfix
        = f.hidden_field :current_user, value: current_user.name
      #user-search-result
        .chat-group-user.clearfix.js-chat-member

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{class: "chat-group-form__label" ,for: "chat_group_チャットメンバー"}チャットメンバー
    .chat-group-form__field--right
      = f.hidden_field :current_user, class: "chat-group-form__input", id: "user-search-field", value: current_user.id
      = f.hidden_field :current_user, class: "chat-group-form__input", id: "user-search-field", value: current_user.name
      .chat-group-form__search.clearfix
        .chat-group-user.clearfix
        = f.hidden_field :user_id, name: "group[user_ids][]", value: current_user.id
      #member-list
        - @members.each do |user|
          .chat-group-user.clearfix.js-chat-member
            %p{class: "chat-group-user__name"}#{user.name}
            = f.hidden_field :user_id, name: "group[user_ids][]", value: user.id
            %a{class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove"}削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "登録する", name: "commit", class: "chat-group-form__action-btn"

app/views/groups/_group.html.haml
= form_for @group do |f|

  -if @group.errors.any?
    .chat-group-form__errors
      #error_explanation
        %h2= "#{ (@group.errors.count) } 件のエラーがあります。"
        %ul
          - @group.errors.full_messages.each do |msg|
            %li= msg


  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label "グループ名",:name , class: "chat-group-form__label",for: "chat_group_name"
    .chat-group-form__field--right
      = f.text_field :name ,placeholder: "グループ名を入力してください" ,class: "chat-group-form__input", id: "chat_group_name"

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"}チャットメンバーを追加
    .chat-group-form__field--right
      %input{type: "text", placeholder: "追加したいユーザー名を入力してください", class: "chat-group-form__input", id: "user-search-field"}
      .chat-group-form__search.clearfix
        .chat-group-user.clearfix
        = f.hidden_field :current_user, value: current_user.name
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label{class: "chat-group-form__label" ,for: "chat_group_チャットメンバー"}チャットメンバー
    .chat-group-form__field--right
      = f.hidden_field :current_user, class: "chat-group-form__input", id: "user-search-field", value: current_user.id
      = f.hidden_field :current_user, class: "chat-group-form__input", id: "user-search-field", value: current_user.name
      .chat-group-form__search.clearfix
        .chat-group-user.clearfix
        = f.hidden_field :user_id, name: "group[user_ids][]", value: current_user.id
      #member-list
        - @member.each do |user|
          .chat-group-user.clearfix.js-chat-member
            %p{class: "chat-group-user__name"}#{user.name}
            = f.hidden_field :user_id, name: "group[user_ids][]", value: user.id
            %a{class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove"}削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "登録する", name: "commit", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
!!!
.chat-group-form
  %h1 チャットグループ編集
  .edit_chat_group#edit_chat_group_22

  = render partial: "form"

  -# .chat-group-form__field--left
  -# .chat-group-form__field--right
      -# = f.submit "更新する", name: "commit", class: "chat-group-form__action-btn"
  -# .chat-group-form__field.clearfix
  -#   .chat-group-form__field--left
  -#     = f.label "チャットメンバー" ,class: "chat-group-form__label" ,for: "chat_group_チャットメンバー"
  -#   .chat-group-form__field--right
  -#     /グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
  -#     = collection_check_boxes(:group, :user_ids, User.all, :id ,:name)
  -#
  -# .chat-group-form__field.clearfix
  -#   .chat-group-form__field--left
  -#   .chat-group-form__field--right
  -#     = f.submit "更新する", name: "commit", class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
!!!
.wrapper
  .flash
  .leftwrapper
    .leftcontent
      .username
        %h1= current_user.name
        %li.username__icons
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o
          = link_to edit_user_path(current_user.id) do
            %i.fa.fa-cog

      = render partial: "messages/newmessage"

app/views/groups/new.html.haml
!!!
.chat-group-form
  %h1 新規チャットグループ
  .new_chat_group#new_chat_group

    = render partial: "form"


    -# .chat-group-form__field.clearfix
    -#   / <!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    -#   / .chat-group-form__field--left'
    -#   /   %label{class: "chat-group-form__label" ,for: "chat_group_チャットメンバーを追加"}チャットメンバーを追加
    -#
    -#   / .chat-group-form__field--right
    -#   /   .chat-group-form__search.clearfix
    -#   /     = f.text_field :user_ids, placeholder: "追加したいユーザー名を入力してください", class: "chat-group-form__input", id: "user-search-field"
    -#
    -#   /   #user-search-result
    -#
    -# .chat-group-form__field.clearfix
    -#   .chat-group-form__field--left
    -#     = f.label "チャットメンバー", class: "chat-group-form__label", for: "chat_group_チャットメンバーchat_group_チャットメンバー"
    -#
    -#   .chat-group-form__field--right
    -#     / <!-- グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
    -#     / = f.collection_check_boxes(:user_ids, User.all, :id, :name, multiple: true, include_hidden: false) do |b|
    -#     = collection_check_boxes(:group, :user_ids, User.all, :id, :name)
    -#
    -#     / <!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    -#     / <!-- #chat-group-users
    -#     /   .chat-group-user.clearfix#chat-group-user-22
    -#     /     %input{name: 'chat_group[user_ids][]', type: 'hidden', value='22'}
    -#     /     %p{class: 'chat-group-user__name'} seo_kyohei
    -#
    -# .chat-group-form__field.clearfix
    -#   .chat-group-form__field--left
    -#   .chat-group-form__field--right
    -#     = f.submit "登録する", name: "commit", class: "chat-group-form__action-btn", disable_with: "Save"

app/views/layouts/_flash.html.haml
- if flash.present?
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http:{equiv: "Content-Type"}}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
%ul.body__messages
  %li.body__messages_username
    = message.user.name
  %span.body__messages_date
    = time_format(message.created_at)
  %li.body__messages_message
    = message.body if message.body.present?
  %li.body__messages_image
    = image_tag message.image.url if message.image.present?

app/views/messages/_newmessage.html.haml
.groups
  - @groups.each do |group|
    %dl.groups__group-name
      = link_to group_messages_path(group.id) do
        = group.name
    %dt.groups__message
      -if group.messages.pluck(:body).last.present?
        = group.messages.pluck(:body).last
      -elsif group.messages.pluck(:image).last.present?
        画像が投稿されました。
      -else
        まだ投稿されていません。

app/views/messages/index.html.haml
!!!
.wrapper
  .flash
  .leftwrapper
    .leftcontent
      .username
        %h1= current_user.name
        %li.username__icons
          = link_to new_group_path do
            %i.fa.fa-pencil-square-o
          = link_to edit_user_path(current_user.id) do
            %i.fa.fa-cog

      = render partial: "newmessage"

  .rightwrapper
    .rightcontent
      .header
        .header__left
          %h3= @group.name
          %p Member :
          - @member.each do |m|
            %p= m.name
        .header__right
          = link_to edit_group_path(@group) do
            Edit
      .body
        = render @messages
      .footer
        .form
        = form_for [@group, @message] , html: {id: "new_message"} do |f|
          = f.text_field :body, placeholder: "type a message", class: "form__message"
          .form__right
            = f.label :image, class: "form__right_label" do
              = fa_icon "picture-o"
              = f.file_field :image, class: "hide"
          = f.submit "Send", class: "form__submit"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true, class: "input"
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email, class: "input"
        .actions
          = f.submit "Update", class: 'btn'